name: Run Codebase Tests

on:
  push:
    branches:
      - hw2 
  pull_request:
    branches:
      - hw2

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 2  # fetch enough commits to get diff for last change

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install SWIG
      run: sudo apt-get update && sudo apt-get install -y swig

    - name: Install current package
      run: pip install .

    - name: Install pytest
      run: pip install pytest
       
    - name: Install dependencies
      run: pip install -r requirements_colab.txt

    - name: Run tests
      run: pytest tests/test_for_completion_hw2.py
